# Generated by Django 4.2 on 2023-04-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todoitems_createat_todoitems_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='grade',
        ),
    ]
